// Generated by CoffeeScript 1.3.1
(function() {

  Turing.State = (function() {

    State.name = 'State';

    State.kOperationsKey = 'operations';

    State.kNextStateKey = 'nextState';

    function State() {
      this.operations = {};
    }

    State.prototype.getOperations = function() {
      return this.operations;
    };

    State.prototype.addOperations = function(character, operations, nextState) {
      this.operations[character] = {};
      this.operations[character][State.kOperationsKey] = operations;
      return this.operations[character][State.kNextStateKey] = nextState;
    };

    State.prototype.operationsFor = function(character) {
      return this.getValueForCharacter(character, State.kOperationsKey);
    };

    State.prototype.nextStateFor = function(character) {
      return this.getValueForCharacter(character, State.kNextStateKey);
    };

    State.prototype.getValueForCharacter = function(character, keyValue) {
      if (this.operations[character] != null) {
        return this.operations[character][keyValue];
      } else if (this.operations['any'] != null) {
        return this.operations['any'][keyValue];
      } else {
        throw new Error('Encountered invalid symbol.');
      }
    };

    return State;

  })();

}).call(this);
