// Generated by CoffeeScript 1.3.1
(function() {
  var currentOperations, drawCurrentTapeSnapshot, drawThickLine, init, machineTimer, nextOperation, shiftHeadLeft, shiftHeadRight, shiftTapeStep, shiftTimer, stateMachine, tape;

  machineTimer = null;

  shiftTimer = null;

  drawThickLine = function(xCoord) {
    var context;
    context = document.getElementById("paperTapeCanvas").getContext('2d');
    context.lineWidth = 5;
    context.beginPath();
    context.moveTo(xCoord, 0);
    context.lineTo(xCoord, 50);
    context.closePath();
    return context.stroke();
  };

  drawCurrentTapeSnapshot = function() {
    var context, i, _i;
    context = document.getElementById("paperTapeCanvas").getContext('2d');
    context.lineWidth = 1;
    context.font = "bold 48px sans-serif";
    context.clearRect(0, 0, context.canvas.width, context.canvas.height);
    for (i = _i = 0; _i <= 8; i = ++_i) {
      context.beginPath;
      context.moveTo(i * 100, 0);
      context.lineTo(i * 100, 50);
      context.strokeStyle = "#000";
      context.closePath();
      context.stroke();
      context.fillText(tape.characterAtIndex(i), i * 100 + 35, 40);
    }
    drawThickLine(400);
    return drawThickLine(500);
  };

  shiftTapeStep = function(xCoordFunc, inc, stepNum, stepIndices) {
    var charIndex, context, i, _i, _len;
    context = document.getElementById("paperTapeCanvas").getContext('2d');
    context.lineWidth = 1;
    context.font = "bold 48px sans-serif";
    context.strokeStyle = "#000";
    if (stepNum <= 100) {
      context.clearRect(0, 0, context.canvas.width, context.canvas.height);
      for (_i = 0, _len = stepIndices.length; _i < _len; _i++) {
        i = stepIndices[_i];
        context.beginPath();
        context.moveTo(xCoordFunc(i, stepNum), 0);
        context.lineTo(xCoordFunc(i, stepNum), 50);
        context.closePath();
        context.stroke();
        charIndex = i - 1;
        if (inc) {
          charIndex = i + 1;
        }
        context.fillText(tape.characterAtIndex(charIndex), xCoordFunc(i, stepNum) + 35, 40);
      }
      stepNum += 1;
      return shiftTimer = setTimeout(function() {
        return shiftTapeStep(xCoordFunc, inc, stepNum, stepIndices);
      }, 1);
    } else {
      drawThickLine(400);
      return drawThickLine(500);
    }
  };

  shiftHeadLeft = function() {
    return shiftTapeStep(function(boxIndex, stepNum) {
      return boxIndex * 100 + stepNum;
    }, true, 0, [0, 1, 2, 3, 4, 5, 6, 7, 8]);
  };

  shiftHeadRight = function() {
    return shiftTapeStep(function(boxIndex, stepNum) {
      return boxIndex * 100 - stepNum;
    }, false, 0, [1, 2, 3, 4, 5, 6, 7, 8, 9]);
  };

  stateMachine = new Turing.StateMachine;

  tape = new Turing.Tape(4);

  currentOperations = [];

  nextOperation = function() {
    var operation;
    if (0 === currentOperations.length) {
      currentOperations = stateMachine.processState(tape.currentCharacter());
    } else {
      operation = currentOperations.shift();
      tape.doOperation(operation);
      switch (operation) {
        case "E":
          drawCurrentTapeSnapshot();
          break;
        case "L":
          shiftHeadLeft();
          break;
        case "R":
          shiftHeadRight();
          break;
        default:
          drawCurrentTapeSnapshot();
      }
    }
    return machineTimer = setTimeout(nextOperation, 500);
  };

  init = function() {
    var addRowToTable, clearTable;
    drawCurrentTapeSnapshot();
    clearTable = function() {
      var addRowCell, addedRows;
      clearInterval(machineTimer);
      clearInterval(shiftTimer);
      stateMachine.reset();
      tape.reset();
      drawCurrentTapeSnapshot();
      addedRows = $('.addedRow');
      if (addedRows.length > 0) {
        addedRows.remove();
        addRowCell = $(document.createElement('i'));
        addRowCell.addClass('icon-plus-sign');
        return $('#stateMachineTable th:first-child').html('<i class="icon-plus-sign"></i>');
      }
    };
    addRowToTable = function() {
      var newRow;
      newRow = $('#stateRowTemplate').clone();
      newRow.id = '';
      newRow.addClass('addedRow');
      $('#stateMachineTable').append(newRow);
      return newRow;
    };
    $(function() {
      return $('#clear-machine').on('click', clearTable);
    });
    $(function() {
      return $('#start-machine').on('click', function() {
        var i, row, stateRawData, stateRows, statesRawData, td, _i, _j, _len;
        try {
          stateRows = $('#stateMachineTable .addedRow');
          statesRawData = [];
          for (_i = 0, _len = stateRows.length; _i < _len; _i++) {
            row = stateRows[_i];
            stateRawData = [];
            for (i = _j = 1; _j <= 4; i = ++_j) {
              td = $(row).children()[i];
              stateRawData.push($(td).children()[0].value.trim());
            }
            statesRawData.push(stateRawData);
          }
          stateMachine.setup(statesRawData);
        } catch (error) {
          alert(error);
        }
        currentOperations = stateMachine.processState("");
        return nextOperation();
      });
    });
    $(function() {
      return $('#stateMachineTable').on('click', '.icon-plus-sign', function(eventObject) {
        addRowToTable();
        return $(eventObject.target).parent().empty();
      });
    });
    $(function() {
      return $('#alternating-machine').on('click', function() {
        var i, newRow, rowValues, textFields, _i, _len, _ref, _results;
        clearTable();
        _ref = Turing.machines.alternatingOnesAndZeros;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          rowValues = _ref[_i];
          newRow = addRowToTable();
          textFields = $(newRow).children('td').children('input');
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (i = _j = 0, _ref1 = rowValues.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
              _results1.push(textFields[i].value = rowValues[i]);
            }
            return _results1;
          })());
        }
        return _results;
      });
    });
    $(function() {
      return $('#one-fourth-machine').on('click', function() {
        var i, newRow, rowValues, textFields, _i, _len, _ref, _results;
        clearTable();
        _ref = Turing.machines.oneFourth;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          rowValues = _ref[_i];
          newRow = addRowToTable();
          textFields = $(newRow).children('td').children('input');
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (i = _j = 0, _ref1 = rowValues.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
              _results1.push(textFields[i].value = rowValues[i]);
            }
            return _results1;
          })());
        }
        return _results;
      });
    });
    return $(function() {
      return $('#sequences-of-ones').on('click', function() {
        var i, newRow, rowValues, textFields, _i, _len, _ref, _results;
        clearTable();
        _ref = Turing.machines.sequencesOfOnes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          rowValues = _ref[_i];
          newRow = addRowToTable();
          textFields = $(newRow).children('td').children('input');
          _results.push((function() {
            var _j, _ref1, _results1;
            _results1 = [];
            for (i = _j = 0, _ref1 = rowValues.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
              _results1.push(textFields[i].value = rowValues[i]);
            }
            return _results1;
          })());
        }
        return _results;
      });
    });
  };

  $(document).ready(init);

}).call(this);
